name: Mayhem for API
on:
  push:
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Start API
      run: |
        ./gradlew localDistro
        pushd build/distribution/local/elasticsearch-*/bin/
        ELASTIC_PASSWORD=password ./elasticsearch -E discovery.type=single-node -E xpack.security.enabled=false &
        for i in {1..90} ; do curl --silent http://localhost:9200/ -H 'Authorization: Basic ZWxhc3RpYzpwYXNzd29yZA==' && echo API up && break; sleep 5s; done


    - name: Run Mayhem for API to check for vulnerabilities
      uses: ForAllSecure/mapi-action@v1
      with:
        mapi-token: ${{secrets.MAPI_TOKEN}}
        api-url: http://localhost:9200/
        api-spec: https://cloud.elastic.co/api/v1/api-docs/spec.json
        target: elasticsearch
        duration: 600s
        run-args: |
          --header-auth
          Authorization: Basic ZWxhc3RpYzpwYXNzd29yZA==